version: "3.7"
services:
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "9000:80"
        environment:
            WORDPRESS_DB_HOST: db
        env_file: .env
        working_dir: /var/www/html
        volumes:
            - ./themes/frames:/var/www/html/wp-content/themes/frames
            - ./plugins/wpc-utils:/var/www/html/wp-content/plugins/wp-utils
    db:
        image: mysql:5.7
        restart: always
        env_file: .env
