version: "3.7"
services:
    wordpress:
        image: wordpress:latest
        restart: always
        ports:
            - "9000:80"
        environment:
            WORDPRESS_DB_HOST: db
        env_file: .env
        volumes:
            - ./themes/frames:/var/www/html/wp-content/themes/frames
            - ./plugins/wp-utils:/var/www/html/wp-content/plugins/wp-utils
    db:
        image: mysql:5.7
        restart: always
        env_file: .env
